services:
  - type: web
    name: line-weather-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app_web.py"
    plan: free

  - type: worker
    name: line-weather-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app_worker.py"
    plan: free
