services:
  - type: web
    name: line-weather-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

  - type: worker
    name: line-weather-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app_worker.py

cronjobs:
  - name: morning-weather-push
    schedule: "20 4 * * *"  # 台灣 12:20
    path: /push_weather
  - name: evening-weather-push
    schedule: "0 13 * * *"  # 台灣 21:00
    path: /push_weather
