services:
  - type: web
    name: weather-bot-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

  - type: worker
    name: weather-bot-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app_worker.py
cronjobs:
  - name: morning-weather-push
    schedule: "25 3 * * *"  # 台灣11:25
    path: /push_weather
  - name: evening-weather-push
    schedule: "0 13 * * *"  # 台灣21:00
    path: /push_weather
