services:
  - type: web
    name: line-weather-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

  - type: worker
    name: line-weather-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app_worker.py
    cronjobs:
      - name: morning-weather-push
        schedule: "40 3 * * *"  # 台灣時間 11:40 AM
        path: /push_weather
      - name: evening-weather-push
        schedule: "0 13 * * *"  # 台灣時間 09:00 PM
        path: /push_weather
